title: Coffey Recipes
email: kevdougful@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the online cookbook for the Coffey family (and whoever else wants to
  contribute). If you have a recipe you'd like to share contact kevdougful@gmail.com
  and he'll get into the mix. If you're code inclined, help maintain and improve
  the site by contributing to the repository at https://github.com/kevdougful/recipe-book
baseurl: "/recipe-book" # the subpath of your site, e.g. /blog
url: "http://www.kevdougful.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kevdougful
github_username:  kevdougful

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
